export const phd = [
  "Chemistry",
  "Applied Geology",
  "Applied Geophysics",
  "Mathematics & Computing",
  "Physics",
  "Chemical Engineering",
  "Civil Engineering",
  "Computer Science & Engineering",
  "Electrical Engineering",
  "Electronics Engineering",
  "Fuel, Minerals & Metallurgical Engineering",
  "Environmental Science & Engineering",
  "Humanities & Social Sciences",
  "Management Studies",
  "Mechanical Engineering",
  "Mining Machinery Engineering",
  "Mining Engineering",
  "Petroleum Engineering",
];
